# Generated by Django 6.0.2 on 2026-02-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('processed_text', models.TextField(blank=True, null=True)),
                ('unique_words', models.TextField(blank=True, null=True)),
                ('word_count', models.IntegerField(default=0)),
                ('frequency', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
